import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useSession, signIn, signOut } from "next-auth/react";

import CreateTodo from "../components/CreateTodo";
import Todo from "../components/Todos";
import ToolOptions from "../components/ToolOptions";
import styles from "./index.module.css";

import { listTodos, createTodo, updateTodo, deleteTodos } from "../API";

import { Amplify, API, graphqlOperation } from "aws-amplify";
import awsconfig from "../aws-exports";
import * as subscriptions from "../graphql/subscriptions";

Amplify.configure(awsconfig);

let todoMap = new Map();

export default function Home({ todos }) {
  const { data: session } = useSession();
  const [todoList, setTodoList] = useState([]);
  const [tab, setTab] = useState("all");
  const [todo, setTodo] = useState();
  let createSubscription;
  let updateSubscription;
  let deleteSubscription;

  useEffect(() => {
    setUpSubscriptions();

    return () => {
      createSubscription.unsubscribe();
      updateSubscription.unsubscribe();
      deleteSubscription.unsubscribe();
    };
  }, []);

  useEffect(() => {
    if (session) {
      listAllTodos();
    }
  }, [session]);

  useEffect(() => {
    listAllTodos();
  }, [tab, todo]);

  const setUpSubscriptions = () => {
    createSubscription = API.graphql(
      graphqlOperation(subscriptions.onCreateTodo)
    ).subscribe({
      next: (result) => {
        setTodo(result);
      },
      error: (error) => console.warn(error),
    });

    updateSubscription = API.graphql(
      graphqlOperation(subscriptions.onUpdateTodo)
    ).subscribe({
      next: (result) => {
        setTodo(result);
      },
      error: (error) => console.warn(error),
    });

    deleteSubscription = API.graphql(
      graphqlOperation(subscriptions.onBatchDelete)
    ).subscribe({
      next: (result) => {
        setTodo(result);
      },
      error: (error) => console.warn(error),
    });
  };

  const listAllTodos = async () => {
    if (session) {
      let filter = {
        user: {
          eq: session.user.email,
        },
      };

      // filtering 'completed' status
      if (tab === "todo") {
        filter.completed = { eq: false };
      } else if (tab === "completed") {
        filter.completed = { eq: true };
      }

      await listTodos(filter).then((res) => {
        setTodoList(sortTodoList(res));
      });
    } else {
      if (tab === "todo") {
        setTodoList(
          sortTodoList(
            [...todoMap]
              .map(([key, value]) => value)
              .filter((todo) => !todo.completed)
          )
        );
      } else if (tab === "completed") {
        setTodoList(
          sortTodoList(
            [...todoMap]
              .map(([key, value]) => value)
              .filter((todo) => todo.completed)
          )
        );
      } else {
        setTodoList(sortTodoList([...todoMap].map(([key, value]) => value)));
      }
    }
  };

  const sortTodoList = (todos) => {
    return todos.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
  };

  const onCreateTodo = async (todo) => {
    let currDate = new Date();
    const newTodo = {
      title: todo.title,
      completed: false,
      categories: todo.categories,
    };

    newTodo.id = `todo_${todo.title.replace(
      " ",
      ""
    )}_${currDate.getMonth()}${currDate.getDay()}${currDate.getFullYear()}${currDate.getHours()}${currDate.getMinutes()}${currDate.getSeconds()}${currDate.getMilliseconds()}`;

    if (session) {
      newTodo.user = session.user.email;
      await createTodo(newTodo);
    } else {
      todoMap.set(newTodo.id, { ...newTodo, createdAt: currDate });
      listAllTodos();
    }
  };

  const onUpdateTodo = async (updatedTodo) => {
    if (session) {
      await updateTodo({ ...updatedTodo, user: session.user.email });
    } else {
      todoMap.set(updatedTodo.id, updatedTodo);
      listAllTodos();
    }
  };

  const onDeleteTodos = async (idList) => {
    if (session) {
      await deleteTodos(idList);
    } else {
      for (const id of idList) {
        todoMap.delete(id);
      }
      listAllTodos();
    }
  };

  const onFilterTodos = async (tag) => {
    if (tab === tag) return;
    setTab(tag);
  };

  return (
    <>
      <Head>
        <title>To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <main>
        <div className={styles.pageContainer}>
          <h1 className={styles.title}>To Do</h1>
          <div className={styles.contentContainer}>
            <CreateTodo onCreateTodo={onCreateTodo} />
            <Todo todoList={todoList} onUpdateTodo={onUpdateTodo} />
            <ToolOptions
              tab={tab}
              setTab={setTab}
              todoList={todoList}
              onFilterTodos={onFilterTodos}
              onDeleteTodos={onDeleteTodos}
            />
          </div>
        </div>
      </main>
    </>
  );
}
